Weighted rollout + fast fail
opsani/servo-harness pull request #12
Opened 2021-04-29 09:41 UTC by benburdick

2021-04-29 19:59 UTC, linkous8 requested changes
The configuration sections for ramp up and fast fail haven't been implemented yet. Further, ramp up and fast fail are implemented to always run even if the required input is missing. I would advise against merging this into master until it is backwards compatible and fully up to spec

2021-04-29 19:59 UTC, linkous8 commented on adjust
> +                    results = subprocess.run(['./measure', app_id], input=input_data.encode('UTF-8'), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
The spec doc is a bit ambiguous as to whether `slo_check` section is required to be configured when `ramp_up` is configured but the implementation here effectively makes it required. Please add a check to the config validation logic so that the driver fails right away if misconfigured rather than failing in the middle of an adjustment

2021-04-29 19:59 UTC, linkous8 commented on adjust
> +                      time.sleep(60.0 - ((time.time() - starttime) % 60.0))
- This sleep should be sourced from `harness.slo_check.period` instead of hard coded
- This is rather unlikely, but if the check takes 61 seconds, the driver will sleep for 59 seconds. I think `max(60 - (time.time() - starttime), 0)` would be more desirable in this case

2021-04-29 19:59 UTC, linkous8 commented on adjust
> +                      self.progress - self.progress + 1
- This line is a no-op. Did you meant to assign it?
- Naively incrementing progress can lead to cases of progress > 100 depending on the number of `steps` and how long `step_time` is in the `ramp_up` configuration. You can probably remove this progress update for expediency but if its required to update it here then it should be done so based on how close the current step is to hitting its `step_time` (and also weighted by the number of steps)

2021-04-29 19:59 UTC, linkous8 commented on adjust
> +                  self.progress = self.progress + 10
Naively incrementing progress can lead to cases of progress > 100 depending on the number of `steps` configured. To prevent this and provide more accuracy, you should calculate the weight of each step (100 ÷ number of `steps`) then assign progress to be that weight times the current step number

2021-04-29 19:59 UTC, linkous8 commented on adjust
> +                      failed_check = failed_check + 1
Spec doc defines checks configured with `for` should be considered failing after `for` number of _sequential_ samples. If the returncode is 0, the all failure counters should be reset. If the returncode is 1, any passing checks in the slo check output should also have their failure counters cleared.

In order to determine which checks failed, you'll need to load the slo check stdout json to process the `slo_results` dictionary it provides for this purpose

2021-04-29 19:59 UTC, linkous8 commented on adjust
> +            data["control"]["userdata"]["slo_check"] = 1
Aren't `control` and `userdata` optional properties of the input? If so, the above would raise a KeyError exception and `dict.get` should be used instead

2021-06-03 17:48 UTC, mjdeclerck commented
@benburdick / @linkous8 : What needs to be done to get this closed and merged?

2021-06-04 13:06 UTC, linkous8 commented
@mjdeclerck There are numerous details from the spec doc that are omitted from the pulled pulled branch as indicated in my code review here: https://github.com/opsani/servo-harness/pull/12#pullrequestreview-648519550

According to @benburdick the branch is able to optimize for the client. Perhaps it would be helpful for @pnickolov to take a pass of the requested changes to see if they are really necessary in order to merge this down.

2021-11-02 22:52 UTC, merged